Resources:
  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BooksTable
      AttributeDefinitions:
        - AttributeName: isbn
          AttributeType: S
      KeySchema:
        - AttributeName: isbn
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
